DROP TEMPORARY TABLE IF EXISTS t_o; CREATE TEMPORARY TABLE t_o AS SELECT * FROM orders WHERE id=171;
UPDATE t_o SET id=9201, order_status='pending', payment_status='paid', payment_method='digital_payment', delivery_man_id=NULL, partially_paid_amount=0, confirmed=NULL, canceled=NULL, canceled_by=NULL, refund_applied_at=NULL, refunded=NULL, picked_up=NULL, cancellation_reason=NULL, is_guest=0, user_id=6;
INSERT INTO orders SELECT * FROM t_o;
DROP TEMPORARY TABLE IF EXISTS t_d; CREATE TEMPORARY TABLE t_d AS SELECT * FROM order_details WHERE order_id=171;
UPDATE t_d SET id=9201*10, order_id=9201; INSERT INTO order_details SELECT * FROM t_d;
DROP TEMPORARY TABLE IF EXISTS t_o; CREATE TEMPORARY TABLE t_o AS SELECT * FROM orders WHERE id=171;
UPDATE t_o SET id=9202, order_status='pending', payment_status='partially_paid', payment_method='partial_payment', delivery_man_id=NULL, partially_paid_amount=10, confirmed=NULL, canceled=NULL, canceled_by=NULL, refund_applied_at=NULL, refunded=NULL, picked_up=NULL, cancellation_reason=NULL, is_guest=0, user_id=6;
INSERT INTO orders SELECT * FROM t_o;
DROP TEMPORARY TABLE IF EXISTS t_d; CREATE TEMPORARY TABLE t_d AS SELECT * FROM order_details WHERE order_id=171;
UPDATE t_d SET id=9202*10, order_id=9202; INSERT INTO order_details SELECT * FROM t_d;
DROP TEMPORARY TABLE IF EXISTS t_o; CREATE TEMPORARY TABLE t_o AS SELECT * FROM orders WHERE id=171;
UPDATE t_o SET id=9203, order_status='pending', payment_status='paid', payment_method='digital_payment', delivery_man_id=1, partially_paid_amount=0, confirmed=NULL, canceled=NULL, canceled_by=NULL, refund_applied_at=NULL, refunded=NULL, picked_up=NULL, cancellation_reason=NULL, is_guest=0, user_id=6;
INSERT INTO orders SELECT * FROM t_o;
DROP TEMPORARY TABLE IF EXISTS t_d; CREATE TEMPORARY TABLE t_d AS SELECT * FROM order_details WHERE order_id=171;
UPDATE t_d SET id=9203*10, order_id=9203; INSERT INTO order_details SELECT * FROM t_d;
DROP TEMPORARY TABLE IF EXISTS t_o; CREATE TEMPORARY TABLE t_o AS SELECT * FROM orders WHERE id=171;
UPDATE t_o SET id=9204, order_status='pending', payment_status='partially_paid', payment_method='partial_payment', delivery_man_id=1, partially_paid_amount=10, confirmed=NULL, canceled=NULL, canceled_by=NULL, refund_applied_at=NULL, refunded=NULL, picked_up=NULL, cancellation_reason=NULL, is_guest=0, user_id=6;
INSERT INTO orders SELECT * FROM t_o;
DROP TEMPORARY TABLE IF EXISTS t_d; CREATE TEMPORARY TABLE t_d AS SELECT * FROM order_details WHERE order_id=171;
UPDATE t_d SET id=9204*10, order_id=9204; INSERT INTO order_details SELECT * FROM t_d;
DROP TEMPORARY TABLE IF EXISTS t_o; CREATE TEMPORARY TABLE t_o AS SELECT * FROM orders WHERE id=171;
UPDATE t_o SET id=9205, order_status='pending', payment_status='paid', payment_method='digital_payment', delivery_man_id=1, partially_paid_amount=0, confirmed=NULL, canceled=NULL, canceled_by=NULL, refund_applied_at=NULL, refunded=NULL, picked_up=NULL, cancellation_reason=NULL, is_guest=0, user_id=6;
INSERT INTO orders SELECT * FROM t_o;
DROP TEMPORARY TABLE IF EXISTS t_d; CREATE TEMPORARY TABLE t_d AS SELECT * FROM order_details WHERE order_id=171;
UPDATE t_d SET id=9205*10, order_id=9205; INSERT INTO order_details SELECT * FROM t_d;
DROP TEMPORARY TABLE IF EXISTS t_o; CREATE TEMPORARY TABLE t_o AS SELECT * FROM orders WHERE id=171;
UPDATE t_o SET id=9206, order_status='pending', payment_status='paid', payment_method='digital_payment', delivery_man_id=1, partially_paid_amount=0, confirmed=NULL, canceled=NULL, canceled_by=NULL, refund_applied_at=NULL, refunded=NULL, picked_up=NULL, cancellation_reason=NULL, is_guest=0, user_id=6;
INSERT INTO orders SELECT * FROM t_o;
DROP TEMPORARY TABLE IF EXISTS t_d; CREATE TEMPORARY TABLE t_d AS SELECT * FROM order_details WHERE order_id=171;
UPDATE t_d SET id=9206*10, order_id=9206; INSERT INTO order_details SELECT * FROM t_d;
DROP TEMPORARY TABLE IF EXISTS t_o; CREATE TEMPORARY TABLE t_o AS SELECT * FROM orders WHERE id=171;
UPDATE t_o SET id=9207, order_status='pending', payment_status='paid', payment_method='digital_payment', delivery_man_id=NULL, partially_paid_amount=0, confirmed=NULL, canceled=NULL, canceled_by=NULL, refund_applied_at=NULL, refunded=NULL, picked_up=NULL, cancellation_reason=NULL, is_guest=0, user_id=6;
INSERT INTO orders SELECT * FROM t_o;
DROP TEMPORARY TABLE IF EXISTS t_d; CREATE TEMPORARY TABLE t_d AS SELECT * FROM order_details WHERE order_id=171;
UPDATE t_d SET id=9207*10, order_id=9207; INSERT INTO order_details SELECT * FROM t_d;
DROP TEMPORARY TABLE IF EXISTS t_o; CREATE TEMPORARY TABLE t_o AS SELECT * FROM orders WHERE id=171;
UPDATE t_o SET id=9208, order_status='pending', payment_status='paid', payment_method='digital_payment', delivery_man_id=1, partially_paid_amount=0, confirmed=NULL, canceled=NULL, canceled_by=NULL, refund_applied_at=NULL, refunded=NULL, picked_up=NULL, cancellation_reason=NULL, is_guest=0, user_id=6;
INSERT INTO orders SELECT * FROM t_o;
DROP TEMPORARY TABLE IF EXISTS t_d; CREATE TEMPORARY TABLE t_d AS SELECT * FROM order_details WHERE order_id=171;
UPDATE t_d SET id=9208*10, order_id=9208; INSERT INTO order_details SELECT * FROM t_d;
DROP TEMPORARY TABLE IF EXISTS t_o; CREATE TEMPORARY TABLE t_o AS SELECT * FROM orders WHERE id=153;
UPDATE t_o SET id=9211, order_status='pending', payment_status='paid', payment_method='digital_payment', delivery_man_id=NULL, partially_paid_amount=0, confirmed=NULL, canceled=NULL, canceled_by=NULL, refund_applied_at=NULL, refunded=NULL, picked_up=NULL, cancellation_reason=NULL, is_guest=0, user_id=6;
INSERT INTO orders SELECT * FROM t_o;
DROP TEMPORARY TABLE IF EXISTS t_o; CREATE TEMPORARY TABLE t_o AS SELECT * FROM orders WHERE id=153;
UPDATE t_o SET id=9212, order_status='accepted', payment_status='paid', payment_method='digital_payment', delivery_man_id=1, partially_paid_amount=0, confirmed=NULL, canceled=NULL, canceled_by=NULL, refund_applied_at=NULL, refunded=NULL, picked_up=NULL, cancellation_reason=NULL, is_guest=0, user_id=6;
INSERT INTO orders SELECT * FROM t_o;
DROP TEMPORARY TABLE IF EXISTS t_o; CREATE TEMPORARY TABLE t_o AS SELECT * FROM orders WHERE id=153;
UPDATE t_o SET id=9213, order_status='canceled', payment_status='paid', payment_method='digital_payment', delivery_man_id=1, partially_paid_amount=0, confirmed=NULL, canceled=NULL, canceled_by=NULL, refund_applied_at=NULL, refunded=NULL, picked_up=NULL, cancellation_reason=NULL, is_guest=0, user_id=6;
INSERT INTO orders SELECT * FROM t_o;
DROP TEMPORARY TABLE IF EXISTS t_o; CREATE TEMPORARY TABLE t_o AS SELECT * FROM orders WHERE id=153;
UPDATE t_o SET id=9214, order_status='canceled', payment_status='paid', payment_method='digital_payment', delivery_man_id=1, partially_paid_amount=0, confirmed=NULL, canceled=NULL, canceled_by=NULL, refund_applied_at=NULL, refunded=NULL, picked_up=NULL, cancellation_reason=NULL, is_guest=0, user_id=6;
INSERT INTO orders SELECT * FROM t_o;
INSERT INTO parcel_cancellations (order_id,reason,cancel_by,note,return_otp,return_fee,return_fee_payment_status,before_pickup,created_at,updated_at) VALUES
 (9213,'[]','deliveryman','qa4091',1234,0,'unpaid',0,NOW(),NOW()),
 (9214,'[]','deliveryman','qa4091',1234,0,'unpaid',0,NOW(),NOW());
UPDATE orders SET canceled=NOW(), canceled_by='deliveryman' WHERE id IN (9213,9214);
UPDATE admin_wallets SET digital_received=1000 WHERE id=1;
UPDATE delivery_men SET current_orders=3 WHERE id=1;
UPDATE business_settings SET value='1' WHERE `key`='canceled_by_deliveryman';
