import sys; sys.path.insert(0,"/private/tmp/claude-501/-Users-Apple-Projects-nears/a7f5d4bb-4211-4dfc-9952-11437c9104f3/scratchpad")
from q4108 import *
section("P0 DB proof + AC5 forgot-password uniformity + pending codes")
print("cache:clear ->", reset_state())
print("cache rows before:", sel("select count(*) from cache"))
r1=req("cust unreg email wrong", "cust_verify", {"verification_method":"email","email":"nobody.4108@demo.com","reset_token":"111111"})
print("cache rows after 1 req:", sel("select count(*) from cache"))
print("pwreset keys:", sel("select `key`, value, expiration from cache where `key` like '%pwreset:attempts:%'"))
log("DB PROOF: pwreset cache rows after a verify-token call on port 8408: " + sel("select `key`, value from cache where `key` like '%pwreset:attempts:%'"))
section("AC5 forgot-password")
a=req("cust forgot REGISTERED email", "cust_forgot", {"verification_method":"email","email":"james.wilson@demo.com"})
b=req("cust forgot UNREG email", "cust_forgot", {"verification_method":"email","email":"nobody.4108@demo.com"})
c=req("cust forgot REGISTERED phone", "cust_forgot", {"verification_method":"phone","phone":"+101600000002"})
d=req("cust forgot UNREG phone", "cust_forgot", {"verification_method":"phone","phone":"+101699999999"})
e=req("dm forgot REGISTERED", "dm_forgot", {"phone":"+101700000002"})
f=req("dm forgot UNREG", "dm_forgot", {"phone":"+101799999999"})
print("uniform cust email:", sig(a)==sig(b), " cust phone:", sig(c)==sig(d), " dm:", sig(e)==sig(f))
print(sel("select id,email,phone,token,created_at,otp_hit_count,created_by from password_resets"))
