# NEARS-3996 step 4 QA - OWN mutation list (written before reading the engineer/independent logs). tip cf67afd23 line numbers.
O='UserApp/lib/features/store/controllers/store_discovery_owner.dart'
C='UserApp/lib/features/store/controllers/store_controller.dart'
def E(f,l,o,n): return (f,l,o,n)
M=[]
def m(id,desc,*edits): M.append((id,desc,list(edits)))
# ---- port + shims
m('P1','shim _filterType constant all',E(O,29,'_port.filterType',"'all'"))
m('P2','shim _storeType reads filterType',E(O,30,'_port.storeType','_port.filterType'))
m('P3','shim _storeType setter no-op',E(O,31,'_port.storeType = value','null'))
m('P4','shim _type setter writes storeType',E(O,32,'_port.type = value','_port.storeType = value'))
m('P5','shim hasDeliveryOrigin negated',E(O,33,'_port.hasDeliveryOrigin','!_port.hasDeliveryOrigin'))
m('P6','shim update no notify',E(O,34,'_port.notify()','null'))
m('P7','facade port filterType reads _storeType',E(C,2226,'_controller._filterType','_controller._storeType'))
m('P8','facade port storeType reads _filterType',E(C,2228,'_controller._storeType','_controller._filterType'))
m('P9','facade port storeType setter writes _filterType',E(C,2230,'_controller._storeType = value','_controller._filterType = value'))
m('P10','facade port type setter no-op',E(C,2232,'_controller._type = value','null'))
m('P11','facade port hasDeliveryOrigin always true',E(C,2234,'_controller.hasDeliveryOrigin','true'))
m('P12','facade port notify dropped',E(C,2236,'_controller.update()','null'))
m('P13','facade port notify carries an id',E(C,2236,'_controller.update()',"_controller.update(['x'])"))
# ---- new owner methods
m('N1','clearStoreModel writes empty model',E(O,75,'_storeModel = null;','_storeModel = StoreModel(stores: <Store>[], totalSize: 0, offset: 1);'))
m('N2','replacePopular aliases the argument',E(O,79,'_popularStoreList = [];','_popularStoreList = stores;'),E(O,80,'_popularStoreList!.addAll(stores);',''))
m('N3','replaceLatest aliases the argument',E(O,84,'_latestStoreList = [];','_latestStoreList = stores;'),E(O,85,'_latestStoreList!.addAll(stores);',''))
m('N4','replacePopular reverses',E(O,80,'addAll(stores)','addAll(stores.reversed)'))
m('N5','replaceLatest skips first',E(O,85,'addAll(stores)','addAll(stores.skip(1))'))
m('N6','replacePopular fills latest',E(O,80,'_popularStoreList!.addAll','_latestStoreList!.addAll'),E(O,79,'_popularStoreList = [];','_popularStoreList = []; _latestStoreList = [];'))
m('N7','clearForZone keeps popular',E(O,89,'_popularStoreList = null;',''))
m('N8','clearForZone keeps latest',E(O,90,'_latestStoreList = null;',''))
m('N9','clearForZone keeps featured',E(O,91,'_featuredStoreList = null;',''))
m('N10','clearForZone keeps storeModel',E(O,92,'_storeModel = null;',''))
m('N11','clearForZone keeps storeLoadFailed',E(O,93,'_storeLoadFailed = false;',''))
m('N12','clearForZone keeps popular failed',E(O,94,'_popularAllStoreListFailed = false;',''))
m('N13','clearForZone keeps latest failed',E(O,95,'_latestAllStoreListFailed = false;',''))
m('N14','clearForZone keeps featured failed',E(O,96,'_featuredAllStoreListFailed = false;',''))
m('N15','clearForZone sets storeLoadFailed true',E(O,93,'_storeLoadFailed = false;','_storeLoadFailed = true;'))
m('N16','clearForZone bumps session id',E(O,96,'_featuredAllStoreListFailed = false;','_featuredAllStoreListFailed = false; _storeListSessionId++;'))
m('N17','clearForZone resets the session id',E(O,96,'_featuredAllStoreListFailed = false;','_featuredAllStoreListFailed = false; _storeListSessionId = 0;'))
# ---- facade retargeted sites + delegates
m('F1','open-first reads facade getter not owner field',E(C,85,'_discovery.storeModel?.stores','storeModel?.stores'))
m('F2','open-first null check via facade getter',E(C,119,'_discovery.storeModel == null','storeModel == null'))
m('F3','nearestStoreId reads facade getter',E(C,396,'_discovery.storeModel?.stores','storeModel?.stores'))
m('F4','nearestStoreId scans null list',E(C,396,'_discovery.storeModel?.stores','null'))
m('F5','recommended-item reload no longer nulls the model',E(C,514,'_discovery.clearStoreModel();',''))
m('F6','recommended-item reload clears whole zone',E(C,514,'_discovery.clearStoreModel()','_discovery.clearForZone()'))
m('F7','setPopularFromHomeAll writes latest',E(C,694,'replacePopularStores','replaceLatestStores'))
m('F8','setLatestFromHomeAll writes popular',E(C,701,'replaceLatestStores','replacePopularStores'))
m('F9','setPopularFromHomeAll no notify',E(C,695,'update();',''))
m('F10','setLatestFromHomeAll no notify',E(C,702,'update();',''))
m('F11','clearZoneStores skips owner reset',E(C,717,'_discovery.clearForZone();',''))
m('F12','clearZoneStores keeps recommended list',E(C,718,'_recommendedStoreList = null;',''))
m('F13','clearZoneStores keeps visitAgain list',E(C,719,'_visitAgainStoreList = null;',''))
m('F14','clearZoneStores keeps recommended failed flag',E(C,720,'_recommendedAllStoreListFailed = false;',''))
m('F15','clearZoneStores no notify',E(C,721,'update();',''))
m('F16','activeAllStoreList featured -> latest',E(C,2049,'_discovery.featuredStoreList','_discovery.latestStoreList'))
m('F17','activeAllStoreList popular -> latest',E(C,2051,'_discovery.popularStoreList','_discovery.latestStoreList'))
m('F18','activeAllStoreList latest -> popular',E(C,2054,'_discovery.latestStoreList','_discovery.popularStoreList'))
m('F19','activeAllStoreList popular via facade getter',E(C,2051,'_discovery.popularStoreList','popularStoreList'))
m('F20','activeAllStoreListFailed featured -> latest',E(C,2067,'_discovery.featuredAllStoreListFailed','_discovery.latestAllStoreListFailed'))
m('F21','activeAllStoreListFailed popular -> featured',E(C,2069,'_discovery.popularAllStoreListFailed','_discovery.featuredAllStoreListFailed'))
m('F22','activeAllStoreListFailed latest -> popular',E(C,2072,'_discovery.latestAllStoreListFailed','_discovery.popularAllStoreListFailed'))
m('F23','activeAllStoreListFailed featured via facade getter',E(C,2067,'_discovery.featuredAllStoreListFailed','featuredAllStoreListFailed'))
m('D1','getStoreList delegate source fixed local',E(C,593,'source: source','source: DataSourceEnum.local'))
m('D2','getStoreList delegate drops emptyOnClientFailure',E(C,594,'emptyOnClientFailure: emptyOnClientFailure','emptyOnClientFailure: false'))
m('D3','getStoreList delegate drops onListSettled',E(C,595,'onListSettled: onListSettled','onListSettled: null'))
m('D4','getStoreList default source client',E(C,587,'DataSourceEnum.local','DataSourceEnum.client'))
m('D5','getStoreList default emptyOnClientFailure true',E(C,588,'= false','= true'))
m('D6','getPopularStoreList default dataSource client',E(C,728,'DataSourceEnum.local','DataSourceEnum.client'))
m('D7','getPopularStoreList default fromRecall true',E(C,729,'= false','= true'))
m('D8','getPopularStoreList delegate -> latest',E(C,730,'_discovery.getPopularStoreList','_discovery.getLatestStoreList'))
m('D9','getLatestStoreList delegate -> popular',E(C,744,'_discovery.getLatestStoreList','_discovery.getPopularStoreList'))
m('D10','getFeaturedStoreList delegate fixed local',E(C,754,'dataSource: dataSource','dataSource: DataSourceEnum.local'))
m('D11','getLatestStoreList delegate drops fromRecall',E(C,744,'_discovery.getLatestStoreList','_discovery.getLatestStoreList'),)  # placeholder replaced below
m('G1','getter storeModel -> null',E(C,65,'_discovery.storeModel','null'))
m('G2','getter storeLoadFailed -> popular failed',E(C,157,'_discovery.storeLoadFailed','_discovery.popularAllStoreListFailed'))
m('G3','getter popular failed -> latest failed',E(C,159,'_discovery.popularAllStoreListFailed','_discovery.latestAllStoreListFailed'))
m('G4','getter latest failed -> featured failed',E(C,161,'_discovery.latestAllStoreListFailed','_discovery.featuredAllStoreListFailed'))
m('G5','getter featured failed -> popular failed',E(C,163,'_discovery.featuredAllStoreListFailed','_discovery.popularAllStoreListFailed'))
m('G6','getter session id constant 0',E(C,168,'_discovery.storeListSessionId','0'))
m('G7','getter popular -> latest list',E(C,170,'_discovery.popularStoreList','_discovery.latestStoreList'))
m('G8','getter latest -> featured list',E(C,172,'_discovery.latestStoreList','_discovery.featuredStoreList'))
m('G9','getter featured -> popular list',E(C,174,'_discovery.featuredStoreList','_discovery.popularStoreList'))
# ---- getStoreList body
m('S1','nearest fallback && -> ||',E(O,117,"&& !hasDeliveryOrigin","|| !hasDeliveryOrigin"))
m('S2','nearest fallback to fastest',E(O,118,"'all'","'fastest'"))
m('S3','nearest fallback only for page 1 sentinel (drops write)',E(O,118,"_storeType = 'all';",''))
m('S4','reload keeps model',E(O,121,'_storeModel = null;',''))
m('S5','reload keeps failed flag',E(O,122,'_storeLoadFailed = false;',''))
m('S6','session bump by 2',E(O,123,'_storeListSessionId++;','_storeListSessionId += 2;'))
m('S7','session bump dropped',E(O,123,'_storeListSessionId++;',''))
m('S8','reload notify dropped',E(O,124,'update();',''))
m('S9','local branch for offset<=1 only matters at 0 (offset==1 -> offset<2)',E(O,127,'offset == 1','offset < 2'))
m('S10','local call source client',E(O,132,'DataSourceEnum.local','DataSourceEnum.client'))
m('S11','local call swaps filter and store type',E(O,130,'_filterType','_storeType'),E(O,131,'_storeType','_filterType'))
m('S12','local settle callback dropped',E(O,135,'onListSettled?.call();',''))
m('S13','recursion asks next offset',E(O,137,'offset,','offset + 1,'))
m('S14','recursion drops emptyOnClientFailure',E(O,140,'emptyOnClientFailure: emptyOnClientFailure','emptyOnClientFailure: false'))
m('S15','recursion drops onListSettled',E(O,141,'onListSettled: onListSettled','onListSettled: null'))
m('S16','recursion reload true',E(O,138,'false','true'))
m('S17','client call source local',E(O,148,'DataSourceEnum.client','DataSourceEnum.local'))
m('S18','client call passes storeType first',E(O,146,'_filterType','_storeType'),E(O,147,'_storeType','_filterType'))
m('S19','synthetic-empty guard drops emptyOnClientFailure',E(O,152,'emptyOnClientFailure &&',''))
m('S20','synthetic-empty guard _storeModel != null',E(O,153,'_storeModel == null','_storeModel != null'))
m('S21','synthetic-empty guard offset >= 1',E(O,151,'offset == 1','offset >= 1'))
m('S22','synthetic model offset 2',E(O,157,'offset: 1','offset: 2'))
m('S23','synthetic model total 1',E(O,157,'totalSize: 0','totalSize: 1'))
m('S24','synthetic branch flag false',E(O,158,'_storeLoadFailed = true;','_storeLoadFailed = false;'))
m('S25','synthetic branch no notify',E(O,159,'update();',''))
m('S26','client settle only offset>1',E(O,163,'offset == 1','offset > 1'))
m('S27','client settle callback dropped',E(O,164,'onListSettled?.call();',''))
m('S28','return always true',E(O,167,'storeModel != null','true'))
m('S29','return inverted',E(O,167,'storeModel != null','storeModel == null'))
# ---- _prepareStoreModel / analytics
m('R1','prepare page1 flag not cleared',E(O,174,'_storeLoadFailed = false;',''))
m('R2','prepare page>1 totalSize not copied',E(O,176,'_storeModel!.totalSize = storeModel.totalSize;',''))
m('R3','prepare page>1 offset not copied',E(O,177,'_storeModel!.offset = storeModel.offset;',''))
m('R4','prepare page>1 prepends',E(O,178,'.addAll(','.insertAll(0, '))
m('R5','prepare analytics dropped',E(O,180,'_logStoreListAnalytics(storeModel);',''))
m('R6','prepare notify dropped',E(O,181,'update();',''))
m('R7','prepare page1 keeps old model',E(O,173,'_storeModel = storeModel;',''))
m('A1','analytics registered guard inverted',E(O,194,'!Get.isRegistered','Get.isRegistered'))
m('A2','analytics preview test inverted',E(O,201,'isNotEmpty','isEmpty'))
m('A3','analytics position zero based',E(O,210,'i + 1','i'))
m('A4','analytics withPopular = total',E(O,217,'withPopular','stores.length'))
m('A5','analytics list id changed',E(O,213,"'stores_list'","'store_list'") if False else E(O,214,"'stores_list'","'store_list'"))
m('A6','analytics count counts raw (incl null) entries',E(O,215,'stores.length','(storeModel.stores?.length ?? 0)'))
# ---- popular
m('U1','popular type write dropped',E(O,228,'_type = type;',''))
m('U2','popular reload keeps list',E(O,230,'_popularStoreList = null;',''))
m('U3','popular reload keeps failed',E(O,231,'_popularAllStoreListFailed = false;',''))
m('U4','popular notify inverted',E(O,233,'if (notify)','if (!notify)'))
m('U5','popular fetch guard drops reload',E(O,236,'|| reload ',''))
m('U6','popular fetch guard drops fromRecall',E(O,236,'|| fromRecall',''))
m('U7','popular local call source client',E(O,241,'DataSourceEnum.local','DataSourceEnum.client'))
m('U8','popular local call type fixed',E(O,240,'type,',"'all',"))
m('U9','popular local assign dropped',E(O,245,'_popularStoreList!.addAll(popularStoreList);',''))
m('U10','popular local update dropped',E(O,247,'update();',''))
m('U11','popular recursion notify true',E(O,251,'notify','true'))
m('U12','popular recursion fromRecall false',E(O,253,'true','false'))
m('U13','popular recursion type fixed',E(O,250,'type,',"'all',"))
m('U14','popular client success keeps failed',E(O,263,'_popularAllStoreListFailed = false;',''))
m('U15','popular failure guard inverted',E(O,264,'_popularStoreList == null','_popularStoreList != null'))
m('U16','popular failure flag false',E(O,268,'_popularAllStoreListFailed = true;','_popularAllStoreListFailed = false;'))
m('U17','popular client update dropped',E(O,270,'update();',''))
m('U18','popular client call source local',E(O,258,'DataSourceEnum.client','DataSourceEnum.local'))
# ---- latest
m('L1','latest type write dropped',E(O,282,'_type = type;',''))
m('L2','latest reload keeps list',E(O,284,'_latestStoreList = null;',''))
m('L3','latest reload keeps failed',E(O,285,'_latestAllStoreListFailed = false;',''))
m('L4','latest notify inverted',E(O,287,'if (notify)','if (!notify)'))
m('L5','latest fetch guard drops fromRecall',E(O,290,'|| fromRecall',''))
m('L6','latest fetch guard drops reload',E(O,290,'|| reload ',''))
m('L7','latest local update dropped',E(O,301,'update();',''))
m('L8','latest recursion notify true',E(O,305,'notify','true'))
m('L9','latest recursion fromRecall false',E(O,306,'true','false'))
m('L10','latest client success keeps failed',E(O,317,'_latestAllStoreListFailed = false;',''))
m('L11','latest failure guard inverted',E(O,318,'_latestStoreList == null','_latestStoreList != null'))
m('L12','latest failure flag false',E(O,319,'_latestAllStoreListFailed = true;','_latestAllStoreListFailed = false;'))
m('L13','latest client update dropped',E(O,321,'update();',''))
m('L14','latest local call type fixed',E(O,294,'type,',"'all',"))
m('L15','latest local assign to popular',E(O,299,'_latestStoreList!.addAll','_popularStoreList!.addAll'),E(O,298,'_latestStoreList = [];','_latestStoreList = []; _popularStoreList = [];'))
# ---- featured
m('H1','featured local keeps stale failed flag',E(O,331,'_featuredAllStoreListFailed = false;',''))
m('H2','featured local source follows client',E(O,333,'source: dataSource','source: DataSourceEnum.client'))
m('H3','featured local prepare dropped',E(O,335,'_prepareFeaturedStore(stores);',''))
m('H4','featured local recursion dropped',E(O,336,'getFeaturedStoreList(dataSource: DataSourceEnum.client);',''))
m('H5','featured failure guard && -> ||',E(O,343,'stores == null && _featuredStoreList == null','stores == null || _featuredStoreList == null'))
m('H6','featured failure flag false',E(O,344,'_featuredAllStoreListFailed = true;','_featuredAllStoreListFailed = false;'))
m('H7','featured client prepare dropped',E(O,346,'_prepareFeaturedStore(stores);',''))
m('H8','featured prepare drops flag clear',E(O,352,'_featuredAllStoreListFailed = false;',''))
m('H9','featured prepare drops zone check',E(O,359,'module.pivot!.zoneId == store.zoneId','true'))
m('H10','featured prepare drops module check',E(O,358,'module.id == store.moduleId','true'))
m('H11','featured prepare notify dropped',E(O,366,'update();',''))
m('H12','featured prepare ignores module list',E(O,355,'moduleList.addAll(storeServiceInterface.moduleList());',''))
m('H13','featured client failure guard checks popular list',E(O,343,'_featuredStoreList == null','_popularStoreList == null'))
# fix D11 properly: a real mutation (drop fromRecall in latest delegate)
M[:] = [x for x in M if x[0]!='D11']
m('D11','getLatestStoreList delegate drops fromRecall',E(C,749,'fromRecall: fromRecall','fromRecall: false'))
m('D12','getPopularStoreList delegate drops notify',E(C,733,'notify,','false,'))
m('A4b','analytics withPopularItemsCount = total (re-formulated A4; first A4 broke syntax)',E(O,217,': withPopular,',': stores.length,'))
m('S9b','local branch guard offset==1 -> offset<=1',E(O,127,'offset == 1','offset <= 1'))
m('S9c','local branch guard offset==1 -> offset>=1 (offset 0 would go local)',E(O,127,'offset == 1','offset >= 1'))
